# Uncomment the next line to define a global platform for your project

target 'ObjCTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'ACPCore'
  pod 'ACPCore', :path => '../../'
  pod 'ACPUserProfile', :path => '../../'
  pod 'ACPAudience', :path => '../../'
  
  # Adding these to the podfile won't be required once these pods are public
  pod 'AEPServices', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPCore', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPLifecycle', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPIdentity', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPSignal', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPRulesEngine', :git => 'git@github.com:adobe/aepsdk-rulesengine-ios.git', :branch => 'main'
  pod 'AEPUserProfile', :git => 'git@github.com:adobe/aepsdk-userprofile-ios.git', :branch => 'main'
  pod 'AEPAudience', :git => 'git@github.com:adobe/aepsdk-audience-ios.git', :branch => 'main'
  
  pod 'AEPAssurance'
  
  # Test 3rd parties
  pod 'AppsFlyerAdobeExtension', '~> 5.4'
  pod 'AdformAdobeExtension'
  
end
