# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTestApp
#   pod 'ACPCore'
   pod 'ACPCore', :path => '../../'
   pod 'ACPUserProfile', :path => '../../'
   pod 'ACPAudience', :path => '../../'
   pod 'ACPAnalytics', :path => '../../'

   # Adding these to the podfile won't be required once these pods are public
   pod 'AEPServices', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
   pod 'AEPCore', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
   pod 'AEPLifecycle', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
   pod 'AEPIdentity', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
   pod 'AEPSignal', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
   pod 'AEPRulesEngine', :git => 'git@github.com:adobe/aepsdk-rulesengine-ios.git', :branch => '1.0.0-beta.1'
   pod 'AEPUserProfile', :git => 'git@github.com:adobe/aepsdk-userprofile-ios.git', :branch => 'main'
   pod 'AEPAudience', :git => 'git@github.com:adobe/aepsdk-audience-ios.git', :branch => 'main'
   pod 'AEPAnalytics', :git => 'git@github.com:adobe/aepsdk-analytics-ios.git', :branch => 'main'
end
